[package]
name = "qr_http_resource"
version.workspace = true
edition.workspace = true

[dependencies]

# external
serde.workspace = true
serde_json.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
